# Generated by Django 4.2.1 on 2023-06-17 00:24

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField(verbose_name=builtins.min)),
                ('ename', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('MGR', models.IntegerField(verbose_name=builtins.min)),
                ('Hiredate', models.DateField()),
                ('sal', models.IntegerField()),
                ('deptno', models.IntegerField(verbose_name=builtins.max)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=100)),
                ('deptno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.emp')),
            ],
        ),
    ]
